version: "3.9"
services:
  web:
    build: .
    container_name: web
    restart: always
    ports:
      - "8000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - TZ=Asia/Taipei
  db:
    image: postgres
    container_name: postgres_db_line_bot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes:
  postgres_data: